# @package _global_

defaults:
  - ../base/base
  - _self_

data:
  path: /projects/users/data/UCPH/DeepFetal/projects/preterm/Data/train.json
  batch_size: 128
  val_frac: 0.05
  workers: 64
  ga_cutoff_weeks: 37 #Sharp cutoff (GA < GA_cutoff)
  ehr_data: []
  img_size: [224, 224]
  prefix: /projects/users/data/UCPH/DeepFetal/ultrasound/PNG_processed_no_OCR/
  oversample: True
  oversample_ratio: 1

labels: #Task: [Type of task, loss multiplier, label smoothing, label smoothing parameter]
  tasks:
    preterm: ['bce', 1]
    #GA_reg: ['l2', 0.01]
  label_smoothing: True
  label_smoothing_param: 0.5

training:
  epochs: 150
  vit_frozen_until: 5  #VIT is frozen until this epoch
  ehr_frozen_until: 5 #EHR is frozen until this epoch
  strategy: 'all'

auxiliary:
  method: append

model:
  vit:
    type: vitb16
    weights_path: /projects/users/data/UCPH/DeepFetal/projects/preterm/other_models/weights/model_final.rank_0.pth
    dropout: 0.2
  
  ehr:
    weights_path: 
  
  transform:
    layer_dims: [256]

  pred_head:
    layer_dims: []
    dropout: 0.2
  reg_head:
    layer_dims: []
    dropout: 0.2
    
optimizer:
  type: AdamW
  lr: 5e-5
  lr_decay: 0.65
  weight_decay: 1e-2

  #AdamW
  adamw_params: [0.9,0.999, 1e-8] #Beta1, Beta2, Epsilon
  
scheduler:
  type: cosine_warmup
  num_warmup_steps: 10
  num_cycles: 2 #A multiplier for the cosine scheduler. 2 means two cycles over training
  
device:
  type: cuda
