# @package _global_

defaults:
  - ../base/base
  - _self_
info:
  name: 
  description: 

data:
  path: /projects/users/data/UCPH/DeepFetal/projects/common/populations/preterm/preterm_P1_noMP_34_img_v4/preterm_P1_noMP_34_img_v4_population_train.csv
  test_path: /projects/users/data/UCPH/DeepFetal/projects/common/populations/preterm/preterm_P1_noMP_34_img_v4/preterm_P1_noMP_34_img_v4_population_test.csv
  batch_size: 128
  val_frac: 0.05
  workers: 64
  ga_cutoff_weeks: 34 #Sharp cutoff (GA < GA_cutoff)
  ehr_train_path: ../EHR_extract/outputs/tables/table_EHR_SP_SDS_P1_noMP_v4.yaml.csv
  ehr_test_path: ../EHR_extract/outputs/tables/table_EHR_SP_SDS_P1_noMP_v4.yaml.csv  # same file if EHR is combined
  ehr_data: ['GA_days']  # columns to read from EHR file after merge
  img_data: [PDX, PDY]
  img_size: [224, 224]
  prefix: /projects/users/data/UCPH/DeepFetal/ultrasound/PNG_processed_no_OCR/
  oversample: True
  oversample_ratio: 2

naming:
  CHILD_ID: CPR_BARN
  EHR_CHILD_ID: b_cpr  # join key in EHR file; defaults to CHILD_ID if omitted
  MOTHER_ID: CPR_MOR
  GA_DAYS: GA              # gestational age at birth, always in days
  GA_WEEKS: GA_weeks        # derived in code as GA_DAYS // 7
  IMAGE_PATH: NO_OCR_FILE_PATH

#label / remove / ignore / remove_on_GA 
#(Label as true if cond is true / remove from DF if cond is true / ignore / remove if GA < GA_cutoff)
dataset: 
    progesterone: ignore 
    c-section: ignore #remove_on_GA # handle in population creation. 
    induced: ignore #remove_on_GA

labels: #Task: [Type of task, loss multiplier]
  tasks:
    preterm: ['bce', 1]
    GA_reg: ['l2', 0.01]
  label_smoothing: True
  label_smoothing_param: 0.5

training:
  epochs: 50
  vit_frozen_until: 5  #VIT is frozen until this epoch
  ehr_frozen_until: 5 #EHR is frozen until this epoch
  strategy: 'all'

auxiliary:
  method: append
  strategy: sum

model:
  vit:
    type: vitb16
    weights_path: /projects/users/data/UCPH/DeepFetal/projects/preterm/other_models/weights/oversampled_vitb16.pth #VitB
    #weights_path: /projects/users/data/UCPH/DeepFetal/projects/UltraDino/experiments/vitb16_dinus_preterm_rct/20260424-093943/pretrain/model_final_rank_0.pth #Oversampled
    #weights_path: /projects/users/data/UCPH/DeepFetal/projects/UltraDino/experiments/vitl16_dinus_preterm_rct_5m/20260518-081332/pretrain/model_final.rank_0.pth #VitL oversampled
    dropout: 0.2
  
  ehr:
    type: tabular  # tabular | patient_lookup
    weights_path:
  
  transform:
    layer_dims: [256]

  pred_head:
    layer_dims: []
    dropout: 0.2
  reg_head:
    layer_dims: []
    dropout: 0.2
    
optimizer:
  type: AdamW
  lr: 5e-5
  lr_decay: 0.65
  weight_decay: 1e-2

  #AdamW
  adamw_params: [0.9,0.999, 1e-8] #Beta1, Beta2, Epsilon
  
scheduler:
  type: cosine_warmup
  num_warmup_steps: 10
  num_cycles: 2 #A multiplier for the cosine scheduler. 2 means two cycles over training
  
device:
  type: cuda
