# @package _global_
defaults:
  - _self_

hydra:
  run: # single-run output dir
    dir: outputs/${hydra:job.config_name}/All_Folds_Spacing_CL${now:%Y-%m-%d_%H-%M-%S}

  # pattern for multirun sweeps
  sweep:
    dir: sweeps/${hydra:job.config_name}
    subdir: ${hydra.job.num}          # 0,1,2…

model:

  freeze_encoder: True
  use_proxy: True
  pixel_spacing_embed_dim: 8
  landmarks: True
  
  planes:
    - cervix

  encoder:
    type: vits16
    weights_path: /data/proto/CommonCode/UltraDINO/weights/OLD_CONTAIN_BUG/vits16_dinus_2m/20250123-162345-490406/pretrain/model_final.rank_0.pth #/data/proto/CommonCode/UltraDINO/weights/vits16_dinus_13m/20241205-132822-468746/pretrain/model_final.rank_0.pth

  decoder:
    type: spacing
    outputs:
      - preterm
      - CL

data:
  csv_dir: "/data/proto/Joris/Data/Resampled_Cervix/df_MICCAI_updated.csv"
  split_indexes: ["fold_1","fold_2", "fold_3","fold_4","fold_5","fold_1B","fold_2B","fold_3B","fold_4B","fold_5B"]
  label: "birth_before_week_37"
  input_type: "mask_img"
  resample: True
  
finetune:
  batch_size: 48
  num_workers: 4
  max_epochs: 45
  checkpoints:
    every_n_epochs: 10

# Optimizer hyperparameters
optimizer:
  type: "adamw"  # adam, adamw, sgd
  learning_rate: 1e-4
  weight_decay: 1e-5
  # Adam-specific parameters
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_eps: 1e-8

# Learning rate scheduler
scheduler:
  type: "cosine_warmup"  # none, cosine, cosine_warmup, reduce_on_plateau
  patience: 5    # for reduce_on_plateau
  factor: 0.5    # for reduce_on_plateau
  warmup_epochs: 2
  lr_decay_rate: 0.65
  patch_embed_lr_mult: 0.2

# Regularization
regularization:
  dropout_rate: 0.1
  early_stopping_patience: 0
  early_stopping_metric: "val_loss"
  early_stopping_mode: "min"

device:
  accelerator: "gpu"
  num_devices: 1
  strategy: "ddp"  # Distributed Data Parallel
